# INPUT_FILE="/scratch/lamdo/pyserini_experiments/scirepeval_collections/corpus/scirepeval_search_validation_evaluation.jsonl"  \
# OUTPUT_FOLDER="/scratch/lamdo/keyphrase_generation_retrieval_index/collections/scirepeval_collections/pyserini_formatted_collection_keyphrase_expansion_retrieval_based_ukg_custom_trained_combined_references_v6_position_penalty+length_penalty" \
# INDEX_FOLDER="/scratch/lamdo/keyphrase_generation_retrieval_index/index/scirepeval_search_validation_evaluation_keyphrase_expansion_retrieval_based_ukg_custom_trained_combined_references_v6_position_penalty+length_penalty"\
# KEYWORD_FOR_DOCUMENT_EXPANSION="/scratch/lamdo/precompute_keyphrase_extraction/scirepeval_search_validation_evaluation--retrieval_based_ukg_custom_trained_combined_references_v6_position_penalty+length_penalty.json" \
# DOCUMENT_VECTORS_PATH="/scratch/lamdo/precompute_sparse_representations/custom_trained_combined_references_v6--scirepeval_search_validation_evaluation.jsonl" \
# python scirepeval_search_v2.py


INPUT_FILE="/scratch/lamdo/pyserini_experiments/scirepeval_collections/corpus/scirepeval_search_validation_evaluation.jsonl"  \
OUTPUT_FOLDER="/scratch/lamdo/keyphrase_generation_retrieval_index/collections/scirepeval_collections/splade_based_custom_trained_combined_references_v11-2_position_penalty+length_penalty" \
INDEX_FOLDER="/scratch/lamdo/keyphrase_generation_retrieval_index/index/scirepeval_search_validation_evaluation_v11-2" \
KEYWORD_FOR_DOCUMENT_EXPANSION="/scratch/lamdo/precompute_keyphrase_extraction/scirepeval_search_validation_evaluation--splade_based_custom_trained_combined_references_v11-2_position_penalty+length_penalty.json" \
DOCUMENT_VECTORS_PATH="/scratch/lamdo/precompute_sparse_representations/custom_trained_combined_references_v11-2--scirepeval_search_validation_evaluation.jsonl" \
python scirepeval_search_v2.py


INPUT_FILE="/scratch/lamdo/pyserini_experiments/scirepeval_collections/corpus/scirepeval_search_validation_evaluation.jsonl"  \
OUTPUT_FOLDER="/scratch/lamdo/keyphrase_generation_retrieval_index/collections/scirepeval_collections/splade_based_custom_trained_combined_references_v6-2_position_penalty+length_penalty" \
INDEX_FOLDER="/scratch/lamdo/keyphrase_generation_retrieval_index/index/scirepeval_search_validation_evaluation_v6-2" \
KEYWORD_FOR_DOCUMENT_EXPANSION="/scratch/lamdo/precompute_keyphrase_extraction/scirepeval_search_validation_evaluation--splade_based_custom_trained_combined_references_v6-2_position_penalty+length_penalty.json" \
DOCUMENT_VECTORS_PATH="/scratch/lamdo/precompute_sparse_representations/custom_trained_combined_references_v6-2--scirepeval_search_validation_evaluation.jsonl" \
python scirepeval_search_v2.py