# FILES
defaults:  # (these specify which config FILES to use)
  ############## TRAIN ###################################
  - train/config: splade_keyphrase_informativeness_normal
  - train/data: keyphrase_informativeness_unarxive_intro_relatedwork+scirepeval_search
  - train/model: splade_pretrain_from_distilbert
  ############## INDEX ###################################
  - index: toy
  ############## RETRIEVE ################################
  - retrieve_evaluate: toy
  ############### FLOPS ##################################
  - flops: toy

# Direct PARAMETER setting
config:  # to be provided for each run
  checkpoint_dir: "experiments_unarxive_intro_relatedwork_1citationpersentence+scirepeval_search_v2/debug/checkpoint"
  index_dir: "experiments_unarxive_intro_relatedwork_1citationpersentence+scirepeval_search_v2/debug/index"
  out_dir: "experiments_unarxive_intro_relatedwork_1citationpersentence+scirepeval_search_v2/debug/out"
  fp16: false
