# FILES
defaults:  # (these specify which config FILES to use)
  ############## TRAIN ###################################
  - train/config: splade_keyphrase_informativeness
  - train/data: keyphrase_informativeness_unarxive+scirepeval_search
  - train/model: splade_pretrain_from_distilbert
  ############## INDEX ###################################
  - index: toy
  ############## RETRIEVE ################################
  - retrieve_evaluate: toy
  ############### FLOPS ##################################
  - flops: toy

# Direct PARAMETER setting
config:  # to be provided for each run
  checkpoint_dir: "/home/lamdo/keyphrase_informativeness_test/splade/lamdo_scripts/checkpoints/test"
  index_dir: ???
  out_dir: ???
  fp16: false
